--
-- Author: tony
-- Date: 2014-11-18 16:05:18
--
local PURCHASE_TYPE = {}

PURCHASE_TYPE.IN_APP_BILLING    = 100
PURCHASE_TYPE.IN_APP_PURCHASE   = 200
PURCHASE_TYPE.EASY_2_PAY        = 300
PURCHASE_TYPE.EASY_2_PAY_API    = 301
PURCHASE_TYPE.EASY_2_PAY_WEB    = 302
PURCHASE_TYPE.UNITRY_GAMERTOPUP = 401
PURCHASE_TYPE.UNITRY_GAME_MONEY = 402
PURCHASE_TYPE.MOL_TRUE_MONEY    = 501
PURCHASE_TYPE.MOL_Z_CARD        = 502
PURCHASE_TYPE.MOL_POINT_CARD    = 503
PURCHASE_TYPE.MOL_12_CALL       = 504
PURCHASE_TYPE.BLUE_PAY          = 601
PURCHASE_TYPE.GGPAY_GGCARD      = 701
PURCHASE_TYPE.GGPAY_TMNCC       = 702
PURCHASE_TYPE.GGPAY_DCARD       = 703
PURCHASE_TYPE.LINE_PAY          = 801
PURCHASE_TYPE.LINE_PAY_IOS      = 802
PURCHASE_TYPE.TRUE_SMS_PAY      = 901
PURCHASE_TYPE.BY_CARD           = 1000

return PURCHASE_TYPE
