--
-- Author: Johnny Lee
-- Date: 2014-07-08 18:15:05
--

local DATA_KEYS = {}

DATA_KEYS.USER_DATA              = "USER_DATA"
DATA_KEYS.ROOM_INFO              = "ROOM_INFO"
DATA_KEYS.FRIEND_LIST            = "FRIEND_LIST"
DATA_KEYS.ROOM_CHAT_HISTORY      = "ROOM_CHAT_HISTORY"
DATA_KEYS.CURRENT_HALL_VIEW      = "CURRENT_HALL_VIEW"
DATA_KEYS.SIGNAL_STRENGTH        = "SIGNAL_STRENGTH"
DATA_KEYS.SIT_OR_STAND           = "SIT_OR_STAND"
DATA_KEYS.NEW_MESSAGE            = "NEW_MESSAGE"
DATA_KEYS.BIG_LA_BA_CHAT_HISTORY = "BIG_LA_BA_CHAT_HISTORY" -- 大喇叭消息
DATA_KEYS.TABLE_CONF             = "TABLE_CONF" --场次配置
DATA_KEYS.MOTHER_DAY			 = "MOTHER_DAY"
DATA_KEYS.OPEN_ACT				 ="OPEN_ACT"
DATA_KEYS.CHANGE_FLOWER			 ="CHANGE_FLOWER"
DATA_KEYS.ROOM_CARD_RECORD       = "ROOM_CARD_RECORD"
DATA_KEYS.LAST_ENTER_SCENE       = "LAST_ENTER_SCENE"   --上次停留的场景
DATA_KEYS.MATCH_RANK 			 = "MATCH_RANK"

DATA_KEYS.MATCH_DETAIL = "MATCH_DETAIL"
-- UnionActEntranceOnOff --
DATA_KEYS.UNIONACT_ONOFF       	 = "UNIONACT_ONOFF"

-- FirstChargeFavEntranceOnOff --
DATA_KEYS.CHARGEFAV_ONOFF        = "CHARGEFAV_ONOFF"

-- AlmRechargeFavEntranceOnOff --
DATA_KEYS.ALMRECHARGEFAV_ONOFF        = "ALMRECHARGEFAV_ONOFF"

-- SignInNewIcon --
DATA_KEYS.HALL_SIGNIN_NEW        = "HALL_SIGNIN_NEW"

-- NewstActPaopTip --
DATA_KEYS.HALL_NEWSTACT_PAOPTIP  = "HALL_NEWSTACT_PAOPTIP"

-- SuonaUseTipShow --
DATA_KEYS.SUONA_USETIP_ONOFF = "SUONA_USETIP_ONOFF"

DATA_KEYS.ROOMNOR_LIST_SELECT_TYPE = "ROOMNOR_LIST_SELECT_TYPE"

DATA_KEYS.GRAB_ROOM_LIST = "GRAB_ROOM_LIST"

DATA_KEYS.UPDATE_INFO = "UPDATE_INFO"

DATA_KEYS.FARM_TIPS = "FARM_TIPS"
DATA_KEYS.CASH_WIN_SEND_NUM = "CASH_WIN_SEND_NUM"

DATA_KEYS.TO_MATCH_DATA = "TO_MATCH_DATA"

--DATA_KEYS.EXIT_MATCH_ACTION = "EXIT_MATCH_ACTION"

DATA_KEYS.NEWER_GUIDE_DAY = "NEWER_GUIDE_DAY"

--普通场 or 现金币场
DATA_KEYS.ROOM_INFO_TYPE = "ROOM_INFO_TYPE"

DATA_KEYS.NEW_CARD_RECORD = "NEW_CARD_RECORD" --新牌局记录，只记录自己和庄家。

DATA_KEYS.PRE_GAME_CARDS = "PRE_GAME_CARDS" -- 自己上局手牌以及输赢

return DATA_KEYS
